// <auto-generated />
namespace IceCreamShop.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class SecondRedo : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SecondRedo));
        
        string IMigrationMetadata.Id
        {
            get { return "202107071905347_SecondRedo"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
